### ISSUE TITLE
Inconsistent filename casing 📁

### ISSUE THREAD

**Issue by sofiapoh** [fac18/reactweek-jb#18]
Some of your component files are using capitalised naming and some are all lowercase. When you have a convention for filenames you won’t need to check the casing every time you’re importing

**Comment by oliverjam** [comment]
Also another group had loads of issues with Git/macOS being/not-being case-sensitive, so good to be consistent from the beginning.

**Comment by sofiapoh** [comment]
Yep! Some filesystems are more permissive than others but we shouldn't rely on it.
